### PR TITLE
Grid view

### PR DESCRIPTION
**Pull request by RichyHBM**
This is a first pass on the grid view, for now just using a dialog to display the entry information

### CODE REVIEW

**Comment by flocke** [comment]
There are two things I noticed when trying the PR:
1. I changed the padding and stuff for the cards in one of my last commits which seems to have broken the grid a bit. This is what it currently looks:
screenshot_andotp dev _20180409-095755
2. I tried using the grid layout with the "last used" sorting which doesn't work (it doesn't seem to update the last used timer for the entries). In my opinion we should update the timer when the dialog showing the token is dismissed.

**Comment by RichyHBM** [comment]
Hmm @flocke I thought It would update the last used when you click on an entry to display its popup, i'll look into it!

@gigabytedevelopersinc Do you happen to have a logcat of the crash? I cant think how anything here could affect the backup page

**Comment by RichyHBM** [comment]
Ok, layout should be fixed now, also the last used is now updated when the dialog is dismissed @flocke 

@gigabytedevelopersinc I couldnt repro the crash

**Comment by jonathancross** [comment]
@flocke : Seems this is waiting for your feedback.
@RichyHBM : PR needs a rebase.

**Comment by flocke** [comment]
@RichyHBM There have been a lot of changes since you created this PR, do you think it's still feasible to rebase it or would it be better to start from scratch?

**Comment by RichyHBM** [comment]
> @RichyHBM There have been a lot of changes since you created this PR, do you think it's still feasible to rebase it or would it be better to start from scratch?

Possibly easier/better to just start fresh using this as a reference I think

**Comment by flocke** [comment]
> > @RichyHBM There have been a lot of changes since you created this PR, do you think it's still feasible to rebase it or would it be better to start from scratch?
> 
> Possibly easier/better to just start fresh using this as a reference I think

Ok, then I'm closing this for now.

**Pull request closed without merging**
