### PR TITLE
This implements MOTP support

### PR DESCRIPTION
**Pull request by mantinan**
We had to add pin input and some other stuff.

### CODE REVIEW

**Comment by mantinan** [comment]
I just realised that we had changed defaults at app/src/main/java/org/shadowice/flocke/andotp/Activities/IntroScreenActivity.java and that is probably something that you don't want. Sorry about that.

**Comment by mantinan** [comment]
Ok, I have reviewed it again and have returned to your defaults and also removed the MD5 implementation and recoded it based on Java's one.

**Review by devdreamsolution — APPROVED** [review]

**Comment by flocke** [comment]
I will look over the code in the next couple of days (hopefully).
But I already have a request: could you remove all translations except the English one?
Translations are handled on Crowdin and they will be overwritten if I import the new ones from there.
This will also make it a lot easier to resolve the merge conflicts.

**Comment by mantinan** [comment]
Restored all language files and commited it, hope that fits what you wanted.

**Review by flocke — CHANGES_REQUESTED** [review]
I reviewed the code and found some parts that needed changing. Most of those were introduced by changes I made to the codebase after you already submitted the pull request.
I fixed them locally and created a patch file you can use to update your branch: [motp_fixes.patch.txt](https://github.com/andOTP/andOTP/files/6136564/motp_fixes.patch.txt)
I will merge the pull request after you add those changes.

I also included some minor improvements (like using the `Hex` class from Apache Commons Codec for all Hex-related functions and validating the secret when manually entering it).

**Review by flocke — APPROVED** [review]

**Pull request merged**
