### PR TITLE
Added Scroll to the Database Encryption fragment on Intro screen and forced portrait orientation

### PR DESCRIPTION
**Pull request by enwokoma**
Scrollbars and no need for landscape orientation on the Intro Screens

### CODE REVIEW

**Comment by enwokoma** [comment]
Fixes some of the issues pointed out [here](https://github.com/andOTP/andOTP/pull/144#issuecomment-369530821) in pull request #144

**Comment by flocke** [comment]
I'm gonna look at this tomorrow. If you find a solution for the screenshot problem before that just add it to this request.

**Comment by enwokoma** [comment]
Ok.. That I would do!

**Comment by enwokoma** [comment]
Sorry! I couldn't update this pull request earlier, I just had to make a new Pull Request at #147 for the screenshot issue on Intro Screen! 
This would work well with the latest commit by @flocke at https://github.com/andOTP/andOTP/commit/4366aee3cbdd1ce1732dceb8d848ebf2611786c6

**Pull request merged**
