### PR TITLE
first step towards 0.8.0

### PR DESCRIPTION
**Pull request by ziegenberg**
Updating build environment, tools and dependencies

- update gradle to 6.4
- fixing some build warnings

Updating documentation

- updating readme reflecting changes in tools and dependencies
- updating changelog reflecting changes in tools and dependencies
- updating copyright notes

_rebasing onto master from time to time_

### CODE REVIEW

**Comment by ziegenberg** [comment]
The build passed after fixing the travis config: https://travis-ci.org/github/andOTP/andOTP/builds/684514545

**Comment by ziegenberg** [comment]
@flocke are those changes you would actually favour, or are they not desired?

**Comment by ziegenberg** [comment]
rebased onto current master

**Comment by ziegenberg** [comment]
Build Zeiten sind jetzt bei ca. 1 Sekunde, wenn die Build Caches genutzt werden.

**Comment by flocke** [comment]
@ziegenberg I merged the `storage_access` branch to `master`, which included some of my own first adaptions for 0.8.0. So some of the changes in this PR are now redundant, but I am still interested in a lot of the other stuff you added. If you want you can now rebase it, mark it ready for review and I will merge it as soon as possible.

**Comment by ziegenberg** [comment]
Build runs through and succeeds. Although [it produces a myriad of build warnings](https://travis-ci.org/github/andOTP/andOTP/jobs/696530167) we can now work on.

**Pull request merged**
