### PR TITLE
EntryThumbnail: Add Electronic Arts thumb

### PR DESCRIPTION
**Pull request by rafifos**
This needs to be built and tested, since my internet connection doesn't allow me to download Android Studio (or Android SDK).

### CODE REVIEW

**Comment by RichyHBM** [comment]
I'm not sure if this is necessary as we already have Origin

**Comment by h4ndshake** [comment]
I'm not sure how I can resize the vector without installing Android SDK (or Studio), since atm I don't have the necessary connection to do so.

**Comment by flocke** [comment]
I'm gonna take a look at this later today. But as @RichyHBM already said, do we really need this as we already have the Origin logo? Shouldn't those two be for the same account?

**Comment by h4ndshake** [comment]
Apparently, EA and Origin are different accounts, my guess is that Origin is treated as only the store and the EA account is for everything else (EA access, it's forum, etc.)

**Comment by flocke** [comment]
Alright, can you link me the SVG you used for the icon?

**Comment by rafifos** [comment]
Sure.

https://commons.wikimedia.org/wiki/File:Electronic-Arts-Logo.svg

**Pull request closed without merging**
