### PR TITLE
Implemented #311. OTP details will turn red if it's about to expire in 8 seconds.

### PR DESCRIPTION
**Pull request by Ullas-Aithal**
- Changes color to red if TOTP and STEAM OTP expires in 8 seconds
- Added dark red and light red colors into themes. Color referred from material.io

### CODE REVIEW

**Comment by flocke** [comment]
I like the idea, but I have two suggestions:

1. I would only change the color of the actual token, not the label, issuer, tags as well. Also I would not change the color of the "Hidden" text or the images.
2. There should be a setting to enable/disable this behavior. It can be on by default in my opinion, but the user should have the option to disable it.

If you want I can merge your PR as it is and implement the changes myself, but if you want to you can do it as well.

**Comment by Ullas-Aithal** [comment]
@flocke, I vaguely remember LastPass changing the color of everything and thought I would do the same here. I'll change it.

I'll update the pull request with your suggestions.

**Comment by Ullas-Aithal** [comment]
@flocke, I've implemented your suggestions. 

There's one case where when you turn off the highlight feature while the token is currently being highlighted, the color gets stuck at red because the view won't be redrawn again while you're in the app. 

I've used the existing functionality to recreate activities when there's a change to some preferences. Let me know if you want me to use some other methods like updating the text color for each entry, clearing and resetting the adapter etc.

**Comment by flocke** [comment]
@Ullas-Aithal That looks good to me. But I think we only need to recreate the MainActivity, not the SettingsActivity as well. I will merge it and remove the recreation of the SettingsActivity myself, it's just one line after all. Thank you a lot for this PR!

**Pull request merged**
