### PR TITLE
[KO] Korean Localization, Translation

### PR DESCRIPTION
**Pull request by papercore-dev**
**01. Added Korean locales**
**02. Added Korean screenshots**

### CODE REVIEW

**Comment by vachan-maker** [comment]
@redev-5c how did you localize the screenshots?

**Comment by redev-5c** [comment]
Simple PowerPoint work.

**Comment by vachan-maker** [comment]
That's it.
Can you explain a little more? Where did you get the files? Also doesn't the screenshots have English in it. How did you hide or remove them? 

> 
> 
> Simple PowerPoint work.

**Comment by redev-5c** [comment]
> That's it?
> Can you explain a little more? Where did you get the files? Also doesn't the screenshots have English in it. How did you hide or remove them?
> 
> > Simple PowerPoint work.

I've downloaded every English screenshots and edited part where English existed.
For removing it, just make white, filled rectangle in your image.
[https://imgur.com/a/t80CHS6](url)

**Comment by vachan-maker** [comment]
> 
> 
> > That's it?
> > Can you explain a little more? Where did you get the files? Also doesn't the screenshots have English in it. How did you hide or remove them?
> > > Simple PowerPoint work.
> 
> I've downloaded every English screenshots and edited part where English existed.
> For removing it, just make white, filled rectangle in your image.
> [https://imgur.com/a/t80CHS6](url)

Thank you for the reply

**Review by devdreamsolution — APPROVED** [review]

**Comment by flocke** [comment]
Please move all translation work to Crowdin

**Pull request closed without merging**
