### PR TITLE
Add thumbnails for Heroku and npm

### PR DESCRIPTION
**Pull request by mbertram**
Add thumbnails for heroku (https://brand.heroku.com/) and npm (https://github.com/npm/logos).

### CODE REVIEW

**Comment by RichyHBM** [comment]
Can we see if the NPM vector looks acceptable with a 198x198 size?
So changing the android:width/height and viewportWidth/Height

Too big images can crash lower memory devices so I prefer to cap vectors at 256 by 256

**Comment by mbertram** [comment]
@RichyHBM Resized the logo to 198x198, still looks acceptable on a high-res screen. Thanks.

**Comment by mbertram** [comment]
No particular reason. Caused by the toolchain I chose for scaling the SVG. Should be fixed now.

**Comment by RichyHBM** [comment]
OK, no worries!
FYI, I usually just open the XML in sublime/notepad and edit it manually

**Comment by RichyHBM** [comment]
@flocke this looks foot to merge in to me

**Comment by flocke** [comment]
Sounds good. As always I'm not home over the weekend. Will merge it on  Monday.

**Pull request merged**
