### PR TITLE
Add tumbnails for milestone 0.6.3

### PR DESCRIPTION
**Pull request by RichyHBM**
This adds thumbnails for:
adguard #320
apache #328
cobranded #318
docusign #325
fritz  #306
paysafecard #307
pypi #344 
ripe ncc #275
uber #303
wasabi #336

### CODE REVIEW

**Comment by RichyHBM** [comment]
Added Digidentity #348

**Comment by RichyHBM** [comment]
Add #353 #352 #354

**Comment by RichyHBM** [comment]
Add #337 #312

**Comment by flocke** [comment]
@RichyHBM Could you maybe fix the EntryThumbnail.java file so I can merge this? I just merged a few other PRs which broke this one :fearful:

**Comment by RichyHBM** [comment]
Should be good to go, but let me know if there are any issues as I just used github directly to resolve which I have never used before

**Pull request merged**
