### PR TITLE
 split token with a space every three letters

### PR DESCRIPTION
**Pull request by DanielWeigl**
Split the token string with an space every 3rd letter - its imo easier to copy it that way by hand

image

### CODE REVIEW

**Comment by RichyHBM** [comment]
You seem to set the unformatted token to the tag of the text field, I'm not sure what that tag is (or what its meant to be used for) but would it not be better to take the token and remove any spaces from it when clicking on copy rather than using the tag field?

**Comment by flocke** [comment]
I don't mind the use of the tag. From what I could get from my short reading that's exactly what the tag field is supposed to be used for (to store additional data in a View without needing a extra data structure).

**Comment by flocke** [comment]
I have one additional request before merging this: Please also add a setting where the user can define the length of the blocks (with a default of 3). Maybe some users prefer to split it in groups of 2 letters instead. And please use a VNTNumberPickerPreference for that (like it's done for the label size).

**Comment by DanielWeigl** [comment]
Settings is implemented, i choose to use a ListPreference instead of VNTNumberPickerPreference to also provide a clear setting for "Dont split"  (otherwise it would be "0" - which might not be clear for all user)

**Comment by DanielWeigl** [comment]
@RichyHBM 

> but would it not be better to take the token and remove any spaces from it when clicking on copy rather than using the tag field?

i prefer to prevent going from rawData->formattedData->rawData if possible. If we choose to implement different formats in future (eg, "123-456"), this does not work anymore

**Comment by flocke** [comment]
I currently focus all my intention on the [custom-encryption](https://github.com/andOTP/andOTP/tree/custom-encryption) branch and am holding of on merging any pull requests until that is done.
Once I have finished with that I will merge this one, the code looks good in my opinion.

**Comment by flocke** [comment]
For some reason I had to fix the merge conflicts manually ...

**Pull request merged**
