### PR TITLE
Update tooling

### PR DESCRIPTION
**Pull request by ziegenberg**
Updating build environment, tools, dependencies and travis build

 - update compileSdkVersion to 30
 - update buildToolsVersion to 30.0.3
 - update targetSdkVersion to 30
 - update androidx.media:media to 1.2.1
 - update androidx.constraintlayout:constraintlayout to 2.0.4
 - update androidx.lifecycle to 2.3.0
 - update com.android.tools:desugar_jdk_libs to 1.1.5
 - update com.google.android.material:material to 1.3.0
 - pin com.google.zxing:core version below 3.4

### CODE REVIEW

**Comment by flocke** [comment]
@ziegenberg Is this still relevant? I updated some stuff recently so we might not need this anymore. In any case this would probably need a rebase and to be moved out of draft.

**Comment by ziegenberg** [comment]
I'll have a look and rebase

**Comment by ziegenberg** [comment]
rebased.

the automatic build still fails because of this "bug": https://issuetracker.google.com/issues/162255866

**Comment by ziegenberg** [comment]
I updated the version declaration for `com.google.zxing:core` using gradle version DSL, so it's not only in the comment but also Gradle get's it and Androit Lint doesn't complain about newer version.

**Comment by ziegenberg** [comment]
And I changed the `distributionUrl` in the Gradle wrapper to `https\://services.gradle.org/distributions/gradle-6.5-all.zip` so it provides Gradle API/DSL documentation.

**Pull request merged**
