### PR TITLE
Remove custom backup agent and use default one

### LINKED ISSUE #341: Android backup can cause data loss if relied on between 2 re-installs
A while back I noticed whilst having to twice reinstall my phones OS that when you restore from the Android backup service, the settings arent being backedup/restored, this can mean that if you restore and then have to wipe your device again, it is possible that the default setting of using android backup is set to false and the data on google backup is wiped.

The fast solution would be to set the default value of `settings_key_enable_android_backup_service` in `app/src/main/res/xml/preferences.xml` to true, this would guarantee that when you restore a previous backup android keeps backing up your data.

There is then a further task to investigate if and/or why the preferences arent getting restored

### PR DESCRIPTION
**Pull request by RichyHBM**
Fixes #341

### CODE REVIEW

**Comment by flocke** [comment]
Does this also backup the database file if the KeyStore encryption is used?
Because in that case a restore should result in a crashing app.

**Comment by RichyHBM** [comment]
It would backup all files under the data folder, so yes. But AFAIK that's the current behaviour?

**Comment by RichyHBM** [comment]
I looked into this a bit more and it seems the current setup actually works fine, I don't know how I did it that one time for it to not sync, maybe I didn't wait enough time for Android backup to kick in

**Comment by RichyHBM** [comment]
So what I am saying, is actually we could leave as is and close this PR and the associated bug

**Comment by flocke** [comment]
But as it is currently the Android Sync option can only be enabled when the 
password encryption is used. So it effectively won't backup with the KeyStore.

If it works then let's keep it like this for now. But I'm all for simplifing the settings, so maybe we could remove the option and let the backup agent check which encryption is used and backup according to this? If we do this we should keep the warning you added to the description of the KeyStore encryption.

**Comment by RichyHBM** [comment]
Sounds like a good plan to me, maybe we just leave as is and visit this in the rewrite

**Comment by RichyHBM** [comment]
Closing for now to clean up 0.6.3

**Comment by flocke** [comment]
If I merge this one, #342 can be closed, correct?

**Comment by RichyHBM** [comment]
Thats right, yup

**Comment by RichyHBM** [comment]
Does this PR require anything more?

**Comment by flocke** [comment]
I'm still thinking about this. If we use the default backup agent it will backup the database file even if it uses the KeyStore encryption. And I that case the app will crash after restore on a new phone because the KeyStore entry is missing after the restore.

**Comment by RichyHBM** [comment]
I see, would it be feasable to make it wipe all data on install if it expects a keystore to exsist and it doesnt? Or show a popup?

**Comment by RichyHBM** [comment]
I think the original reason for this change was just my missunderstanding and trying to use andOTP before Android had fully restored all data on my phone, I still think there is value in just using the default agent as its one less thing to maintain but I can understand if there are concerns.

That said I think at the least we should then merge in #342 regardless of what we do with this one

**Comment by flocke** [comment]
Yes, I think enabling it by default if it is available is a good thing either way. We can still brainstorm about this one a bit more after the 0.6.4 release. I am all for simplifying the code.

**Comment by jonathancross** [comment]
> We can still brainstorm about this one a bit more after the 0.6.4 release.

[v0.7.0](https://github.com/andOTP/andOTP/releases/tag/v0.7.0) has been released -- any new thoughts on whether or not this PR makes sense?

**Review by devdreamsolution — APPROVED** [review]

**Comment by flocke** [comment]
I think we should keep using our custom agent to prevent problems when using the KeyStore.

At some point I would like to completely remove the KeyStore as database encryption and only allow password-based encryption.
The KeyStore can be added again on top of that to simplify unlocking (e.g. with fingerprint). The advantage of that would be that, even in case the KeyStore fails, the user can always unlock the database with the password.

Once that is implemented (probably not in the near future) we can revisit this.

**Pull request closed without merging**
