### PR TITLE
Append date backup

### PR DESCRIPTION
**Pull request by RichyHBM**
Allows option to auto append the current date-time to the backup filename

### CODE REVIEW

**Comment by RichyHBM** [comment]
I've just realised, when saving the file using file manager it appends (x) if its a duplicate, so this PR may not be needed, it all depends on how the tasker broadcasts work.

I'll do some testing and report back, but for now hold back on merging this in

**Comment by RichyHBM** [comment]
So it adds (x) when saving a file if you select the filename manually, when saving without the file selector it just overrides the file.

I don't think this PR is as needed as first thought so I'll leave it up to you as to whether this should even be merged in

**Comment by flocke** [comment]
Yeah, when using the file selector it appends a number if the file already exists.
Could you maybe expand this PR to also add the date when NOT using the selector so it doesn't always overwrite the files in that case?

**Comment by RichyHBM** [comment]
Yea it already does that, the filename that andOTP uses has the date added so anything saving to a file should be affected

**Pull request merged**
