### PR TITLE
Add thumbnails for binance, bittrex, blockchaininfo, iconomi, kucoin,…

### PR DESCRIPTION
**Pull request by RichyHBM**
… liqui

### CODE REVIEW

**Comment by flocke** [comment]
I'm gonna hold of on merging any pull requests until the whole password-based encryption stuff is finished.

**Comment by RichyHBM** [comment]
Yup, that's fine. Will give me some time to add the other new icons on the list!

**Comment by RichyHBM** [comment]
Latest commit Fixes #103

**Comment by TMHBOFH** [comment]
Hi,
thanks for your work.

I will be nice if you could add the [Seafile](https://github.com/haiwen/seadroid/blob/master/app/src/main/res/drawable-ldpi/icon.png) icon as well.

best regards

**Comment by SuperVirus** [comment]
Hi,
I build the Hurricane Electric SVG: [hurricane_electric.zip](https://github.com/andOTP/andOTP/files/1615470/hurricane_electric.zip)

Adding Gitea would be nice, too:
https://github.com/go-gitea/gitea/blob/master/assets/logo.svg

**Comment by Zegnat** [comment]
If you are looking to update the thumbnails, please revisit some that have become out of date:

1. Dropbox has a new logo. The SVG is available from [their branding page](https://www.dropbox.com/branding), specifically: [Glyph/Dropbox/SVG/DropboxGlyph_Blue.svg](https://www.dropbox.com/scl/fo/0eu2dsn07fy5k0gt5fy74/AABelaoobzsW8ZKJ2u9vnINGa/Glyph/Dropbox/SVG?dl=0&preview=DropboxGlyph_Blue.svg).
2. Kickstarter has a new logo. They publish only EPS files on [their branding page](https://www.kickstarter.com/help/brand_assets), but Wikimedia Commons has an SVG version: [Kickstarter-logo-k-color.svg](https://commons.wikimedia.org/wiki/File:Kickstarter-logo-k-color.svg).

While I am here, let me drop in 2 requests:

1. Tumblr. Logos available as ZIPs with SVG files from [their logo page](https://www.tumblr.com/logo). I would probably go for “Blue on transparent” or “Blue on white”, not sure what the andOTP policy on backgrounds is.
2. Mixer. Logos available as SVG files on GitHub at [mixer/branding-kit](https://github.com/mixer/branding-kit/tree/master/svg). Again, not sure what the background policy of andOTP is so I can’t point you to the definitive one. You will want to use one of the “MixerMerge” files, those are just the “x”-logo rather than the entire word mark.

Sorry for offloading this on you, but I do not have an Android dev environment set up.

**Comment by gigabytedevelopersinc** [comment]
Also add Godaddy (www.godaddy.com)

**Comment by flocke** [comment]
@RichyHBM Do you still want to add something or can I merge this?

**Comment by RichyHBM** [comment]
I think I've added everything asked for so far (that I could find suitable svgs for) merge it in!

**Comment by Zegnat** [comment]
It looks like this specifically did not update the Kickstarter logo? Any particular reason, @RichyHBM? Thanks for the stellar work otherwise!

**Comment by RichyHBM** [comment]
Yes, when importing the svg linked above the image was just a green square, so I think we will need to look for another source

**Comment by Zegnat** [comment]
> when importing the svg linked above the image was just a green square

Interesting. I’ll have another look around. But couldn’t find any other SVG sources previously. Only the ESP. If I do find one I’ll open an issue.

**Pull request merged**
