### PR TITLE
Add feature graphic and screenshots for F-Droid

### PR DESCRIPTION
**Pull request by jaller94**
This PR aims to add screenshots to the listing in the F-Droid store.
Descriptions/ images can either be added to this repo or to https://gitlab.com/fdroid/fdroiddata/tree/master/metadata

The files get updated to the F-Droid store on a release, not by merging this PR.

- [ ] You could also import all metadata from the Google Play store using `fastlane supply init`.

How to add screens to F-Droid: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Fastlane's doc: https://docs.fastlane.tools/actions/supply/#images-and-screenshots

### CODE REVIEW

**Comment by flocke** [comment]
I always wanted to add this stuff to F-Droid. I am currently on the road, I will have a look as soon as I arrive.

**Comment by Poussinou** [comment]
@flocke @jaller94 

> sevenInchScreenshots

I think you should simply rename this directory to `phoneScreenshots` (nothing else to change). This screenshots currently don't appear on F-Droid, probably because of this.

I'm not sure why the official F-Droid docs [say](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) that the other directories are ok, I assume it's simply because this is the "official" fastlane structure...

Anyway, it works when the directory is named `phoneScreenshots` like you can see [here](https://f-droid.org/packages/org.schabi.newpipe/), [here](https://f-droid.org/packages/de.k3b.android.toGoZip/) or [here](https://f-droid.org/packages/com.pitchedapps.frost/) (check the source code of this apps for example).

**Comment by jaller94** [comment]
@Poussinou For me the screenshots do show up correctly in F-Droid 1.4.
screenshot_20181209-134717

**Comment by Poussinou** [comment]
Well, I was talking about the website ([link to the page](https://f-droid.org/packages/org.shadowice.flocke.andotp/))

They also show up for me via the Android client (version 1.5-alpha0)

It looks like we found a crazy bug here xD

**Pull request merged**
