### PR TITLE
Intro screen

### LINKED ISSUE #141: Intro screen on first launch
Instead of just a simple dialog I would like to show the user an intro screen on the first launch of the app (similar to Nextcloud, Substratum, ...). This is something I would like to have before the first stable release on Google Play.

In that intro the user should be able to:
- [x] Choose a database encryption
- [x] Set an authentication method (depending on the encryption this might be optional)

A library that could be used for that can be found here: https://github.com/heinrichreimer/material-intro

### PR DESCRIPTION
**Pull request by flocke**
Closes #141

### CODE REVIEW

**Comment by enwokoma** [comment]
Well, checked it out already, it's not so bad, looks good! 

But, Suggestion: 

1. I don't think disabling screenshots on the intro pages is right (screenshots should only be disabled on default at the MainActivity where the Tokens are shown)! 

2. The Database Encryption section on the Intro Pages looks truncated because it's not vertically scrollable and some text at the bottom of the section is truncated (I can't upload of snapshot showing this bug because I couldn't take a screenshot, it didn't allow me to)! 

3. (Miscellaneous Suggestion): - There should be a button in the About Page or Settings page allowing the user to click on and play the intro/tour guide!

**Comment by flocke** [comment]
Thanks for your feedback!
1. I totally agree with you and I don't really know why the screenshots are disabled in the intro screen. I didn't disable them manually as I did in the MainActivity. I will look into it.
2. It should be scrollable, let me check.
3. Yeah, that's something I have planed for later, for now I will just leave it as a one-time thing.

**Comment by enwokoma** [comment]
Good! 
Great job so far with andOTP! The development progress is just so massive!

**Comment by enwokoma** [comment]
Pull request #146 contains a minor quick fix but, the screenshot problem is what am still trying to work on, if I can fix that too, I could update the pull request or make an entirely new pull request!

**Comment by flocke** [comment]
I'm not sure why we can't take screenshots. I tried `getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE)` in `onCreate()` for the IntroScreenActivity but it didn't work. Seems like I need to do more research.

**Comment by flocke** [comment]
@enwokoma Ok, never mind. I just fixed it in 4366aee3cbdd1ce1732dceb8d848ebf2611786c6.
Turns out the default theme for the intro screen defines `windowIsTranslucent` which means you can see through the window and since the MainActivity is behind it, which is marked as secure, Android prevents screenshots.

**Comment by enwokoma** [comment]
@flocke.. We are unable to take screenshots of the Intro Screen because, the Intro Screen is inherited from the MainActivity and the MainActivity.java has a condition that sets the `FLAG_SECURE` when the `getScreenshotsEnabled` is false and this function in the Settings.java has a default value of false! 
So, this is some sort of polymorphism!

**Comment by enwokoma** [comment]
@flocke.. Just checked out 4366ae. Looks neat but this fix won't work across all devices!

**Comment by flocke** [comment]
Yeah, I'm gonna have to check out some other Android versions in AVDs but it's a first step that makes it work at least on some devices (I now can take screenshots on my device even if `getScreenshotsEnabled` returns `false`).

**Comment by enwokoma** [comment]
I think I have an idea! 
Would update my pull request at #146. The pull request together with your commit at https://github.com/andOTP/andOTP/commit/4366aee3cbdd1ce1732dceb8d848ebf2611786c6 should be the perfect fix

**Comment by enwokoma** [comment]
Check this out #147

**Pull request merged**
