### PR TITLE
Enable android backup by default

### PR DESCRIPTION
**Pull request by RichyHBM**
First step fix for #341

### CODE REVIEW

**Comment by flocke** [comment]
I will merge this as soon as I get home, let's hope it fixes the problem.

**Comment by flocke** [comment]
Closing because of #345

**Comment by RichyHBM** [comment]
This should also probably return true in the settings helper by default, will submit a new commit for that

**Comment by RichyHBM** [comment]
I'm wrong, it already returns true by default, @flocke this should now be good to merge

**Pull request merged**
