### PR TITLE
Thumbnail dark theme

### LINKED ISSUE #88: Dark Thumbnails (nearly) invisible black theme
#### General information

* App version: 0.3.1
* App source: F-Droid
* Android Version: 7.1.2
* Custom ROM: LineageOS 14.1-20171215

#### Problem description
All dark thumbnails are (nearly) invisible if the black theme is selected.

These thumbnails are affected:
* Amazon
* AWS
* AngelList
* Apple
* Bitstamp
* GitHub
* LastPass
* Steam

#### Steps to reproduce
* Switch andOTP to the black theme
* Choose one of the thumbnails listed above

#### Possible solution/workaround
1. Adding an background to all thumbnails
2. Adding an outline around each logo with transparent background
3. Placing an light background behind the/some thumbnails in the black and dark theme
4. Including different thumbnail for dark/black theme, where needed

### PR DESCRIPTION
**Pull request by RichyHBM**
Fixes #88

Adds a white background and small amount of padding to thumbnails for dark themes

### CODE REVIEW

**Comment by flocke** [comment]
I'm not really happy with how this looks ...
Let me try and experiment a little bit based on this patch, maybe I find something to improve it a bit.

**Comment by flocke** [comment]
I'm still not really happy with how it looks with the background. But I have no idea on what to do instead ...

**Comment by RichyHBM** [comment]
Is there anything specifically you don't like about it?

**Comment by flocke** [comment]
I'm not really sure. For some icons (mostly the solid ones) it looks strange with the small white border around it. Maybe I will make some screenshots and ask for opinions.

**Comment by RichyHBM** [comment]
We could set the padding to 0, that would remove the border for solid ones and only give non-solid ones a background?

**Comment by flocke** [comment]
I totally forgot about this one ...
I won't be home for a few days but I will try this as soon as I can.

**Comment by flocke** [comment]
I played around with the PR a little bit and got another idea. What do you guys think of this?

screenshot_andotp_20180226-104739

**Comment by alexanderadam** [comment]
I like it and it is an easy solution.

**Comment by RichyHBM** [comment]
Seconded, I really like the look of it, and it seems an elegant solution

**Comment by SuperVirus** [comment]
Looks good to me, too.
Maybe going for ltgray instead of the white background?

**Comment by flocke** [comment]
@SuperVirus what do you think of this shade? Anything darker and we will lose the contrast in some thumbnails again.

screenshot_andotp_20180226-150846

**Comment by SuperVirus** [comment]
Looks like a good tradeoff, not being as "bright" as the white but preserving good recognizability of the thumbnails.

**Pull request merged**
