### PR TITLE
Added auto theme selection for Android 10 devices

### PR DESCRIPTION
**Pull request by Ullas-Aithal**
This is for #394 

Added theme mode option in settings. This option will be hidden in devices below Android 10 and set to "Auto" by default for Android 10 devices. Two options will be available: "Auto" and "Manual"

If Auto is selected: Theme selection will be disabled. If the device theme is light, light theme will be applied or else dark theme will be applied. This happens automactically. 
While on Manual: Allows the old option to select between light, dark and black themes

I tested this on my device OnePlus 7 Pro (Android 10), Pixel 3XL (Android 10) and Pixel 3 (Android 9)

### CODE REVIEW

**Comment by Ullas-Aithal** [comment]
@flocke, using the same approach as my last pull request, I'm recreating both MainActivity and SettingsActivity if Theme Mode option is changed. I need to recreate SettingsActivity to refresh disabling/enabling theme selection option. 

Let me know if you need me to any changes.

**Comment by Ullas-Aithal** [comment]
A small video demoing the feature: [https://drive.google.com/open?id=1-fz05zH93BPreXw2DBlhFnsVAnWuEYAe](https://drive.google.com/open?id=1-fz05zH93BPreXw2DBlhFnsVAnWuEYAe)

**Comment by viggy96** [comment]
LineageOS 16 which is based on Android 9 also has a global dark theme setting. Will this feature be exposed to these devices?

**Comment by flocke** [comment]
If they implemented it by backporting the changes from Android 10 then yes, otherwise no.

**Comment by flocke** [comment]
I think I will have to close this PR since I plan on reworking the entire theme stuff after the final release of version 0.7.0, which will change a lot. But thank you for your contribution (and your other PRs)!

**Comment by flocke** [comment]
I'm revisiting this PR since the theme rework will have to wait, I just don't have the time to work on it right now.

**Pull request merged**
