### PR TITLE
Broadcast receivers for backups

### PR DESCRIPTION
**Pull request by RichyHBM**
Here are some receivers to trigger backups via tasker/easer

I am currently having issues with the PGP one, I followed the same logic as in BackupActivity but it keeps failing, as I dont know OpenKeystore that well it may be worth someone looking over it, alternatively maybe we remove that receiver for now until we can get it working

### CODE REVIEW

**Comment by RichyHBM** [comment]
Upon further investigation it seems OpenPGP makes use of bindService() internally and that cant be called from a broadcast receiver, so for now I dont think having a receiver for the PGP backup is possible

https://developer.android.com/reference/android/content/Context.html#bindService(android.content.Intent, android.content.ServiceConnection, int)

**Comment by RichyHBM** [comment]
Android 27 doesn't let you use implicit intents, so I was calling it directly with the class name (though that error would have caused it to not work) but the code was being run as it gives a failure notification when called

**Comment by flocke** [comment]
No that I merged the date-time PR for the backups could you maybe update this PR to also honor those settings and append the date and time to the backups?

**Comment by RichyHBM** [comment]
Will do!

**Comment by rodrigoswz** [comment]
Please, how I create a Tasker profile to auto-backup my accounts?

**Comment by flocke** [comment]
@RichyHBM I just tried it and you were almost right. Using Class didn't work for me I had to use Action. To sum it up:

Task -> System -> Send Intent

Action: org.shadowice.flocke.andotp.broadcast.ENCRYPTED_BACKUP
Package: org.shadowice.flocke.andotp

**Pull request merged**
